
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db-utilisateurs'
      - 'POSTGRES_PASSWORD=nasser'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'