version: '3.1'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
    - 3308:3306
    volumes:
    - db_data:/var/lib/mysql
  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
    - 8888:8080
volumes:
  db_data: